import '../globals.css'
import {Inter} from 'next/font/google'
import {Header} from "@/components/Header/Header";
import Head from "next/head";
import styles from '../styles.module.scss'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Head>
            <title>Dashboard</title>
        </Head>
        <main>
            <Header/>
            <div className={styles.main}>
                <div className={styles.layout}>
                    {children}
                </div>
            </div>
        </main>
        </body>
        </html>
    )
}
